sudo: required

language: bash

services:
- docker

env:
  global:
    - secure: UVDc36uUMcSTCmcM6vm+FgvT4RLTJh34JBmlLr4+0rg+BBcynee9E61vLy/PHlKrrsfWzOHwKJy6YsTawU+95fjcC3qcOtuY2K6isc5THVRMEmxp4A8ec11DJUjpPK5Rc7q0r71QgIkL7fP2f2Onp4te6trPCFXuVlsBxEevztsjUA008Q4IojVfvO9tCo+c+ZJIpq7fBw/fhEwczc4kjF2LEH2MnAVQmDsZ+WTF8Ip3jZk8y9EjJhylAyEpZdieTrwjn5RgbNKLndY8pP+aI32CqDUgKSgCf9Y57IjY2bVpEnw5erb+x5/An+bB7S0/4GvVdfCzeO5fIb9eonLIqEFzVFKluR72C4qyEFetRCQL135+TqegOxThsdKyaVOBLZXmnW6ZVVokKU4Z67+XRnAKbez0WvXWa8dgtYz3BtiqCF4m18wNfogk284LzQjBJgTyzos5s+1UwfCEBLTzHW6pcscylVT1bonXgCiDClyviu7gqQMEmW25TParK5h+P8smgQUVg3uHJr/+4OTNjD19QAe9rWG0I0CHilN3PLOXnJLC4S/O2SNG9yQB4ZbEd4FMYcWlEFI3G2QpRzNS06ZhjrImymCPKpn4RyVEHZxtzYya8Z9s5kq6iQoZCaWgjIu/8pAGk1NIjBfnUCoU5hIZ9oCdRudgb/Hfbj+HS7I=
    - secure: nfadkkKEEa3UcEU7lZoSD35ljKtGb4lnn9XbgwCZigp60HEzbTIJ+wS8vIM0K7ElCMKdMrvcrvi61mNidWj27PlXQsPruQuQZWbLY6HauqCZsTxhJD8/Iqqn0+LUbseVVrT5kaysWpV/1diMQdMOR9EmCTN7lvTkRQdENMfOS/xA0hXlnz/cCUrGFiX8h0VgUP+/Qn4v0gIrffuheAPzzRYGtMNdT06NnNsLj0W6fG2L9cu9GK8wtAo0wWGFQH0WG0IVHDmgAnXGet0sRdoumlvnqyYTgWssZUyZISs0sYq81hMuxyRJmXa46uMsUbayo9/2QiKo3NBmLpfuSzBpY7kr8h38mpkI6m4vmF2kpLgS8lkO3YvAHSuSIA04RLKO/rB9O0heZtp4WHF7rztPn3/OwRBufZKq6B6FhFMZcCN+wBr/hQJBa2B8zpQPWqE9WUejcL/XPJ7yFaxKwT4LROiQpJSFS2WZb323rTC+Uth0rS76NIN6kElnV3Qsis9EPesrOW8I6eNH5RKn4toPeTvvD3WTrKuKHaEbofdM/dHjZ7p7AHeaMC0sYC9ZMN9jY/MDPQZeHAFCwjLtj/nToIb8jagR8KRQedPphIAnNOQ4Lxw1/Kva+Px43Mo5fXEgYU/YVZQF+IcS6s8CuN2DvQJNIdhc4vLKbEL2yaFa9n0=
    - secure: VCRlyMWybfQxHiiDQlUeLVtV3v/lyDVvsGAJVuPhrQT1xQPKzTBE0Ts5VyguH4L9ohqfyoBfOmI4shAwUyq7hJF1k6Ia21r1/Cv4j2C/Zw7Kh1jVwF68bZAckrypx8wdt6/hsxQ+pxXkEkF8wd+7v2AdXDiqNwCnuI1hOkUfRjXA42wvzRb5alQA4O0xBzr3K75RAat1TZ2qwPjH1rw4AbZxpUFEY27WT/h0Nj5MuJef+7ci4rIZucyn+2oPsqaVFXf+izafHki+y7rvbKWvI4QSKxMU8vkppklQ4sZrqNd/+FCmB+DgkeF5a5r5xskIo86dWK2tD4FRZbDJ/awpz4ZaootKfN8WLqniIwGsY4AAJn0nCMs0uUx35T7QALNa99MVh97rt34AV/Ld2u3TuX/rKq77jWHXacUFm/5bKguMzFRXifUW5Vl8vF/pu/8AAV9hZ9LzWeXg9ar86/hUvr8ZAE7WSiVutQYnVIJFcBIUB3Sw/c1bOmKQrz237dC5QV6U5g0VKRHGXGvm0zlKayjZf7t/6SVZFh9ssakMjaCwdC03c77s+eLxVB0QIrR0OESfZzXMi3KdmzoU5a5LJor+u0U3um8j1gM6Sak7wB7zogdrttBvgRnZtk8+iQDGJE3XAiYk1Ufi+VkDhNKr7VPVLGN4ZwFg5AxBBOM+dLA=

before_install:
- export REPO=docker.io/rhmap/nagios
- export VERSION=4.0.8
- export BUILD=2
- export DOCKER_REGISTRY=https://index.docker.io/v1/
- docker build -f Dockerfile -t "$REPO:$VERSION-$BUILD" .

after_success:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS" "$DOCKER_REGISTRY"
- export TAG=latest
- docker tag "$REPO:$VERSION-$BUILD" $REPO:$TAG
- docker push "$REPO:$VERSION-$BUILD"
- docker push $REPO:$TAG
- docker rmi "$REPO:$VERSION-$BUILD"
- docker rmi $REPO:$TAG
