sudo: required

language: bash

services:
  - docker

before_install:
  - export REPO=docker.io/rhmap/nagios
  - export VERSION=4.0.8
  - export BUILD=2
  - docker build -f Dockerfile -t "$REPO:$VERSION-$BUILD" .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=latest
  - docker tag -f "$REPO:$VERSION-$BUILD" $REPO:$TAG
  - docker push -f "$REPO:$VERSION-$BUILD"
  - docker push -f $REPO:$TAG
  - docker rmi "$REPO:$VERSION-$BUILD"
  - docker rmi $REPO:$TAG
