sudo: required

language: bash

services:
  - docker

before_install:
  - export REPO=docker.io/rhmap/nagios
  - export VERSION=4.0.8
  - export BUILD=2
  - docker build -f Dockerfile -t "$REPO:$VERSION-$BUILD" .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS https://index.docker.io/v1/
  - export TAG=latest
  - docker tag "$REPO:$VERSION-$BUILD" $REPO:$TAG
  - docker push "$REPO:$VERSION-$BUILD"
  - docker push $REPO:$TAG
  - docker rmi "$REPO:$VERSION-$BUILD"
  - docker rmi $REPO:$TAG
