apiVersion: "v1"
kind: "Template"
metadata:
  name: nagios-poc-template
objects:
  -
    apiVersion: "v1"
    kind: "Service"
    metadata:
      name: "nagios-poc"
    spec:
      selector:
        provider: "rhmap"
        component: "nagios-poc"
      ports:
        -
          protocol: "TCP"
          port: 8080
          targetPort: 8080
  -
    apiVersion: "v1"
    kind: "Route"
    metadata:
      name: "nagios-poc"
    spec:
      host: "${NAGIOS_HOST}"
      to:
        kind: "Service"
        name: "nagios-poc"
      tls:
        termination: "edge"
        insecureEdgeTerminationPolicy: "Allow"
  -
    apiVersion: "v1"
    kind: "DeploymentConfig"
    metadata:
      labels:
        provider: "rhmap"
        component: "nagios-poc"
      name: "nagios-poc"
    spec:
      replicas: 1
      selector:
        provider: "rhmap"
        component: "nagios-poc"
      triggers:
      - type: ConfigChange
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Recreate
      template:
        metadata:
          labels:
            provider: "rhmap"
            component: "nagios-poc"
        spec:
          containers:
          - name: "nagios-poc"
            image: "rhmap/nagios-poc"
            ports:
              - containerPort: 8080
            env:
            - name: "SMTP_SERVER"
              value: "${SMTP_SERVER}"
            - name: "SMTP_FROM_ADDRESS"
              value: "${SMTP_FROM_ADDRESS}"
            - name: "MBAAS_ADMIN_EMAIL"
              value: "${MBAAS_ADMIN_EMAIL}"
            - name: "NAGIOS_USER"
              value: "${NAGIOS_USER}"
            - name: "NAGIOS_PASSWORD"
              value: "${NAGIOS_PASSWORD}"
          volumes:
            - emptyDir:
              name: "nagios-poc-data"
parameters:
-
  description: "Nagios hostname to expose a route as"
  name: NAGIOS_HOST
  required: true
-
  description: "SMTP server address to use for sending alert emails e.g. 1.2.3.4:25"
  name: "SMTP_SERVER"
  value: "localhost"
-
  description: "From email address for alerts"
  name: "SMTP_FROM_ADDRESS"
  value: "aaaaaa@example.com"
-
  description: "To email address for alerts"
  name: "MBAAS_ADMIN_EMAIL"
  value: "root@localhost"
-
  description: "Nagios admin username"
  name: "NAGIOS_USER"
  value: "nagiosadmin"
-
  description: "Nagios admin user password"
  name: "NAGIOS_PASSWORD"
  generate: "expression"
  from: "[a-zA-Z0-9]{10}"